version: 2

jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: govgo/guix:0.0.1
    working_directory: /go/src/github.com/vcaesar/guix
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      #  override:
      # './...' is a relative pattern which means all subdirectories  
      # - run: go get -u github.com/go-vgo/robotgo
      - run: go get -v -t -d ./...
      - run: go test -v ./... 
      # codecov.io
      # - run: go test -v -covermode=count -coverprofile=coverage.out
      # - run: bash <(curl -s https://codecov.io/bash)   